### ISSUE TITLE
Make a new release on GNU ELPA

### ISSUE THREAD

**Issue by skangas** [Malabarba/spinner.el#22]
Please consider making a new release on GNU ELPA to fix some bugs and get rid of the cl deprecation warning.

The last release was 1.7.3 in 2016 according to:
https://elpa.gnu.org/packages/spinner.html

Thanks in advance.

**Comment by keegancsmith** [comment]
@Malabarba friendly ping :)

**Comment by wyuenho** [comment]
@Malabarba you still maintaining your emacs packages?

**Comment by Malabarba** [comment]
Thanks for the friendly pings. I've pushed to Elpa under version 1.7.4. 
It's been a while since my last push to Elpa, but I think I did everything right. :sweat_smile: 
Let me know if it doesn't show up.

@wyuenho 
I try, but it's not part of my routine anymore, so it's hard to find time sometimes and it's easy to forget when I do have time.

**Comment by skangas** [comment]
spinner.el 1.7.4 now seems to be available on GNU ELPA. Thanks for taking care of this request!
